export type SubTest = {
  name: string;
  unit?: string;
  reference?: string;
  method?: string;
};

export type PathologyTest = {
  id: string;
  name: string;
  category: string;
  department: string;
  cost: number;
  sampleType: string;
  method?: string;
  subTests?: SubTest[];
  comments?: string;
};

export const PATHOLOGY_TESTS: PathologyTest[] = [
  {
    id: "cbc",
    name: "Complete Blood Count (CBC)",
    category: "Hematology",
    department: "DEPARTMENT OF HEMATOLOGY",
    cost: 350,
    sampleType: "EDTA Whole Blood",
    method: "Automated Cell Counter",
    subTests: [
      { name: "Hemoglobin", unit: "g/dL", reference: "13.0 - 17.0 (M) / 12.0 - 15.0 (F)", method: "Automated" },
      { name: "Total RBC Count", unit: "million/µL", reference: "4.5 - 5.5 (M) / 3.8 - 4.8 (F)", method: "Automated" },
      { name: "Total WBC Count", unit: "/µL", reference: "4000 - 11000", method: "Automated" },
      { name: "Platelet Count", unit: "lakhs/µL", reference: "1.5 - 4.5", method: "Automated" },
      { name: "Hematocrit (PCV)", unit: "%", reference: "40 - 50 (M) / 36 - 46 (F)", method: "Automated" },
      { name: "MCV (Mean Corpuscular Volume)", unit: "fL", reference: "80 - 100", method: "Automated" },
      { name: "MCH (Mean Corpuscular Hemoglobin)", unit: "pg", reference: "27 - 32", method: "Automated" },
      { name: "MCHC (Mean Corpuscular Hb Conc.)", unit: "g/dL", reference: "32 - 36", method: "Automated" },
      { name: "RDW-CV (Red Cell Distribution Width)", unit: "%", reference: "11.5 - 14.5", method: "Automated" },
      { name: "RDW-SD", unit: "fL", reference: "39 - 46", method: "Automated" },
      { name: "MPV (Mean Platelet Volume)", unit: "fL", reference: "7.5 - 12.5", method: "Automated" },
      { name: "PDW (Platelet Distribution Width)", unit: "fL", reference: "9.0 - 17.0", method: "Automated" },
      { name: "PCT (Plateletcrit)", unit: "%", reference: "0.17 - 0.35", method: "Automated" },
      { name: "P-LCR (Platelet Large Cell Ratio)", unit: "%", reference: "13 - 43", method: "Automated" },
      { name: "Neutrophils", unit: "%", reference: "40 - 70", method: "Automated" },
      { name: "Lymphocytes", unit: "%", reference: "20 - 40", method: "Automated" },
      { name: "Eosinophils", unit: "%", reference: "1 - 6", method: "Automated" },
      { name: "Monocytes", unit: "%", reference: "2 - 10", method: "Automated" },
      { name: "Basophils", unit: "%", reference: "0 - 1", method: "Automated" },
      { name: "Band Cells", unit: "%", reference: "0 - 5", method: "Microscopy" },
      { name: "Neutrophils (Absolute Count)", unit: "/µL", reference: "1800 - 7700", method: "Automated" },
      { name: "Lymphocytes (Absolute Count)", unit: "/µL", reference: "1000 - 4800", method: "Automated" },
      { name: "Eosinophils (Absolute Count)", unit: "/µL", reference: "20 - 500", method: "Automated" },
      { name: "Monocytes (Absolute Count)", unit: "/µL", reference: "200 - 1000", method: "Automated" },
      { name: "Basophils (Absolute Count)", unit: "/µL", reference: "0 - 100", method: "Automated" },
      { name: "Nucleated RBC (NRBC)", unit: "/100 WBC", reference: "0", method: "Automated" },
      { name: "NLR (Neutrophil-Lymphocyte Ratio)", unit: "", reference: "1 - 3", method: "Calculated" },
      { name: "PLR (Platelet-Lymphocyte Ratio)", unit: "", reference: "< 200", method: "Calculated" },
    ],
  },
  {
    id: "lft",
    name: "Liver Function Test (LFT)",
    category: "Biochemistry",
    department: "DEPARTMENT OF CLINICAL BIOCHEMISTRY AND IMMUNOCHEMISTRY",
    cost: 600,
    sampleType: "Serum",
    method: "Spectrophotometry / IFCC",
    subTests: [
      { name: "Total Bilirubin", unit: "mg/dL", reference: "0.2 - 1.2", method: "Diazo Method" },
      { name: "Direct Bilirubin (Conjugated)", unit: "mg/dL", reference: "0.0 - 0.3", method: "Diazo Method" },
      { name: "Indirect Bilirubin (Unconjugated)", unit: "mg/dL", reference: "0.1 - 0.9", method: "Calculated" },
      { name: "SGOT (AST)", unit: "U/L", reference: "5 - 40", method: "IFCC" },
      { name: "SGPT (ALT)", unit: "U/L", reference: "5 - 45", method: "IFCC" },
      { name: "Alkaline Phosphatase (ALP)", unit: "U/L", reference: "40 - 130", method: "IFCC" },
      { name: "GGT (Gamma Glutamyl Transferase)", unit: "U/L", reference: "< 55 (M) / < 38 (F)", method: "IFCC" },
      { name: "Total Protein", unit: "g/dL", reference: "6.0 - 8.3", method: "Biuret" },
      { name: "Albumin", unit: "g/dL", reference: "3.5 - 5.2", method: "BCG Dye Binding" },
      { name: "Globulin", unit: "g/dL", reference: "2.0 - 3.5", method: "Calculated" },
      { name: "A/G Ratio", unit: "", reference: "1.0 - 2.1", method: "Calculated" },
      { name: "LDH (Lactate Dehydrogenase)", unit: "U/L", reference: "120 - 240", method: "IFCC" },
    ],
    comments: "Fasting sample preferred for accurate results.",
  },
  {
    id: "kft",
    name: "Kidney Function Test (KFT)",
    category: "Biochemistry",
    department: "DEPARTMENT OF CLINICAL BIOCHEMISTRY AND IMMUNOCHEMISTRY",
    cost: 550,
    sampleType: "Serum",
    method: "Spectrophotometry",
    subTests: [
      { name: "Blood Urea", unit: "mg/dL", reference: "15 - 40", method: "Urease" },
      { name: "Blood Urea Nitrogen (BUN)", unit: "mg/dL", reference: "7 - 20", method: "Calculated" },
      { name: "Serum Creatinine", unit: "mg/dL", reference: "0.7 - 1.3 (M) / 0.5 - 1.1 (F)", method: "Jaffe's" },
      { name: "BUN / Creatinine Ratio", unit: "", reference: "10 - 20", method: "Calculated" },
      { name: "eGFR (Estimated GFR)", unit: "mL/min/1.73m²", reference: "> 90 (Normal)", method: "CKD-EPI" },
      { name: "Uric Acid", unit: "mg/dL", reference: "3.5 - 7.2 (M) / 2.5 - 6.0 (F)", method: "Uricase" },
      { name: "Sodium (Na+)", unit: "mmol/L", reference: "135 - 145", method: "ISE" },
      { name: "Potassium (K+)", unit: "mmol/L", reference: "3.5 - 5.1", method: "ISE" },
      { name: "Chloride (Cl-)", unit: "mmol/L", reference: "98 - 107", method: "ISE" },
      { name: "Bicarbonate (HCO3-)", unit: "mmol/L", reference: "22 - 29", method: "ISE" },
      { name: "Calcium (Total)", unit: "mg/dL", reference: "8.6 - 10.2", method: "Arsenazo III" },
      { name: "Phosphorus (Inorganic)", unit: "mg/dL", reference: "2.5 - 4.5", method: "Phosphomolybdate" },
      { name: "Magnesium", unit: "mg/dL", reference: "1.7 - 2.4", method: "Calmagite" },
    ],
  },
  {
    id: "lipid",
    name: "Lipid Profile (Basic)",
    category: "Biochemistry",
    department: "DEPARTMENT OF CLINICAL BIOCHEMISTRY AND IMMUNOCHEMISTRY",
    cost: 500,
    sampleType: "Serum",
    method: "Enzymatic",
    subTests: [
      { name: "Total Cholesterol", unit: "mg/dL", reference: "Desirable : < 200\nBorderline : 200-239\nHigh :>= 240", method: "Enzymatic" },
      { name: "Triglycerides", unit: "mg/dL", reference: "Desirable :<161\nBorderline:161-199\nElevated :200-499\nVery High :>499", method: "Glycerol Phosphate Oxidase" },
      { name: "HDL Cholesterol", unit: "mg/dL", reference: "35 - 80", method: "Accelerator Selective Detergent" },
      { name: "LDL Cholesterol", unit: "mg/dL", reference: "optimal (Ideal) <100\nBorderline High:100-129\nHigh : 130-200", method: "Calculated" },
      { name: "VLDL Cholesterol", unit: "mg/dL", reference: "10 - 35", method: "Calculated" },
      { name: "Total / HDL Cholesterol Ratio", unit: "", reference: "3.0 - 5.0", method: "Calculated" },
      { name: "Non HDL Cholesterol", unit: "mg/dL", reference: "Optimal<130\nAbove Optimal 130-159\nHigh >160", method: "Calculated" },
      { name: "LDL / HDL Cholesterol Ratio", unit: "", reference: "< 3.5", method: "Calculated" },
    ],
    comments: "In high risk patients including patient with diabetes (Ref. NCEP III update circulation 110:227, July 13,2004)\n* LDL goal is <100 mg/dl but an optimal goal is LDL <70 mg/dl.\n* It is advised to initiate drug therapy if LDL is >100 mg/dl. Drug therapy is optional if LDL <100 mg/dl.",
  },
  {
    id: "thyroid",
    name: "Thyroid Profile (T3, T4, TSH)",
    category: "Endocrinology",
    department: "DEPARTMENT OF CLINICAL IMMUNOLOGY & SEROLOGY",
    cost: 450,
    sampleType: "Serum",
    method: "CLIA (Chemiluminescent Immunoassay)",
    subTests: [
      { name: "Total T3 (Triiodothyronine)", unit: "ng/mL", reference: "0.8 - 2.0", method: "CLIA" },
      { name: "Total T4 (Thyroxine)", unit: "µg/dL", reference: "5.1 - 14.1", method: "CLIA" },
      { name: "TSH (Thyroid Stimulating Hormone)", unit: "µIU/mL", reference: "0.27 - 4.20", method: "CLIA" },
      { name: "Free T3 (FT3)", unit: "pg/mL", reference: "2.0 - 4.4", method: "CLIA" },
      { name: "Free T4 (FT4)", unit: "ng/dL", reference: "0.93 - 1.70", method: "CLIA" },
    ],
  },
  {
    id: "fbs",
    name: "Fasting Blood Sugar",
    category: "Biochemistry",
    department: "DEPARTMENT OF CLINICAL BIOCHEMISTRY AND IMMUNOCHEMISTRY",
    cost: 100,
    sampleType: "Fluoride Plasma (Fasting)",
    method: "GOD-POD (Glucose Oxidase Peroxidase)",
    subTests: [
      { name: "Glucose - Fasting", unit: "mg/dL", reference: "Normal: 70 - 100\nPre-Diabetes: 101-125\nDiabetes: >= 126", method: "GOD-POD" },
    ],
    comments: "Patient should be fasting for at least 8-10 hours before sample collection.",
  },
  {
    id: "ppbs",
    name: "Postprandial Blood Sugar (PPBS)",
    category: "Biochemistry",
    department: "DEPARTMENT OF CLINICAL BIOCHEMISTRY AND IMMUNOCHEMISTRY",
    cost: 100,
    sampleType: "Fluoride Plasma (Post meal)",
    method: "GOD-POD (Glucose Oxidase Peroxidase)",
    subTests: [
      { name: "Glucose - PP (2hrs Post Meal)", unit: "mg/dL", reference: "Normal: < 140\nPre-Diabetes: 140-199\nDiabetes: >= 200", method: "GOD-POD" },
    ],
    comments: "Sample collected exactly 2 hours after starting a meal.",
  },
  {
    id: "hba1c",
    name: "HbA1c (Glycated Hemoglobin)",
    category: "Biochemistry",
    department: "DEPARTMENT OF CLINICAL BIOCHEMISTRY AND IMMUNOCHEMISTRY",
    cost: 450,
    sampleType: "EDTA Whole Blood",
    method: "HPLC (High Performance Liquid Chromatography)",
    subTests: [
      { name: "HbA1c", unit: "%", reference: "Normal: 4.0 - 5.6\nPre-Diabetes: 5.7-6.4\nDiabetes: >= 6.5", method: "HPLC" },
      { name: "Estimated Average Glucose (eAG)", unit: "mg/dL", reference: "70 - 126 (Non-diabetic)", method: "Calculated" },
      { name: "Mean Blood Glucose", unit: "mg/dL", reference: "< 154 (Target for diabetics)", method: "Calculated" },
    ],
    comments: "HbA1c reflects average blood glucose over the past 2-3 months. Target HbA1c for diabetic patients is < 7.0%.",
  },
  {
    id: "urine",
    name: "Urine Routine Examination",
    category: "Clinical Pathology",
    department: "DEPARTMENT OF CLINICAL PATHOLOGY",
    cost: 200,
    sampleType: "Random Urine (Midstream)",
    subTests: [
      { name: "Colour", reference: "Pale Yellow to Yellow" },
      { name: "Appearance / Transparency", reference: "Clear" },
      { name: "Reaction (pH)", reference: "5.0 - 8.0" },
      { name: "Specific Gravity", reference: "1.005 - 1.030" },
      { name: "Protein (Albumin)", reference: "Nil / Negative" },
      { name: "Glucose (Sugar)", reference: "Nil / Negative" },
      { name: "Ketone Bodies", reference: "Nil / Negative" },
      { name: "Bile Salts", reference: "Nil / Negative" },
      { name: "Bile Pigment (Bilirubin)", reference: "Nil / Negative" },
      { name: "Urobilinogen", unit: "EU/dL", reference: "0.1 - 1.0" },
      { name: "Nitrite", reference: "Negative" },
      { name: "Leukocyte Esterase", reference: "Negative" },
      { name: "Blood (Hemoglobin)", reference: "Negative" },
      { name: "Pus Cells (WBC)", unit: "/hpf", reference: "0 - 5" },
      { name: "Red Blood Cells (RBC)", unit: "/hpf", reference: "0 - 2" },
      { name: "Epithelial Cells", unit: "/hpf", reference: "0 - 5 (Squamous)" },
      { name: "Casts", reference: "Nil / Rare Hyaline" },
      { name: "Crystals", reference: "Nil / Few" },
      { name: "Bacteria", reference: "Nil / Negative" },
      { name: "Yeast Cells", reference: "Absent" },
    ],
  },
  {
    id: "vitd",
    name: "Vitamin D (25-OH)",
    category: "Endocrinology",
    department: "DEPARTMENT OF CLINICAL IMMUNOLOGY & SEROLOGY",
    cost: 1200,
    sampleType: "Serum",
    method: "CLIA (Chemiluminescent Immunoassay)",
    subTests: [
      { name: "25-OH Vitamin D (Total)", unit: "ng/mL", reference: "Deficiency: < 20\nInsufficiency: 20-29\nSufficiency: 30 - 100\nToxicity: > 150", method: "CLIA" },
    ],
    comments: "Values < 20 ng/mL indicate Vitamin D Deficiency. Supplementation is recommended.",
  },
  {
    id: "vitb12",
    name: "Vitamin B12 (Cobalamin)",
    category: "Endocrinology",
    department: "DEPARTMENT OF CLINICAL IMMUNOLOGY & SEROLOGY",
    cost: 800,
    sampleType: "Serum",
    method: "CLIA (Chemiluminescent Immunoassay)",
    subTests: [
      { name: "Vitamin B12 (Cyanocobalamin)", unit: "pg/mL", reference: "Deficiency: < 200\nBorderline: 200-300\nNormal: 300 - 900\nHigh: > 900", method: "CLIA" },
    ],
  },
  {
    id: "esr",
    name: "ESR (Erythrocyte Sedimentation Rate)",
    category: "Hematology",
    department: "DEPARTMENT OF HEMATOLOGY",
    cost: 100,
    sampleType: "EDTA Whole Blood",
    method: "Westergren Method",
    subTests: [
      { name: "ESR (1 Hour)", unit: "mm/hr", reference: "Male: 0 - 20\nFemale: 0 - 30\nChild: 0 - 10", method: "Westergren" },
    ],
  },
  {
    id: "crp",
    name: "C-Reactive Protein (CRP)",
    category: "Immunology",
    department: "DEPARTMENT OF CLINICAL IMMUNOLOGY & SEROLOGY",
    cost: 350,
    sampleType: "Serum",
    method: "Immunoturbidimetry",
    subTests: [
      { name: "CRP (C-Reactive Protein)", unit: "mg/L", reference: "Normal: < 6.0\nMild Elevation: 6-10\nModerate: 10-40\nMarked: > 40", method: "Turbidimetry" },
    ],
    comments: "CRP is a sensitive marker of acute inflammation and tissue injury.",
  },
  {
    id: "dengue",
    name: "Dengue NS1 + IgG/IgM",
    category: "Serology",
    department: "DEPARTMENT OF CLINICAL MICROBIOLOGY & SEROLOGY",
    cost: 900,
    sampleType: "Serum",
    method: "ELISA / Rapid Card Test",
    subTests: [
      { name: "Dengue NS1 Antigen", reference: "Negative", method: "ELISA" },
      { name: "Dengue IgM Antibody", reference: "Negative (< 1.1 Ratio)", method: "ELISA" },
      { name: "Dengue IgG Antibody", reference: "Negative (< 1.1 Ratio)", method: "ELISA" },
    ],
    comments: "NS1 is positive in early acute phase (Day 1-5). IgM appears from Day 3-5 and IgG from Day 7 onwards.",
  },
  {
    id: "typhi",
    name: "Widal Test (Typhoid)",
    category: "Serology",
    department: "DEPARTMENT OF CLINICAL MICROBIOLOGY & SEROLOGY",
    cost: 250,
    sampleType: "Serum",
    method: "Slide Agglutination",
    subTests: [
      { name: "S. Typhi 'O' Antigen", reference: "< 1:80 (Non-significant)", method: "Slide Agglutination" },
      { name: "S. Typhi 'H' Antigen", reference: "< 1:80 (Non-significant)", method: "Slide Agglutination" },
      { name: "S. Paratyphi 'AH' Antigen", reference: "< 1:80 (Non-significant)", method: "Slide Agglutination" },
      { name: "S. Paratyphi 'BH' Antigen", reference: "< 1:80 (Non-significant)", method: "Slide Agglutination" },
    ],
    comments: "Titre >= 1:160 for O and H antigens is considered significant in endemic areas.",
  },
  {
    id: "malaria",
    name: "Malaria Antigen (Rapid)",
    category: "Serology",
    department: "DEPARTMENT OF CLINICAL MICROBIOLOGY & SEROLOGY",
    cost: 250,
    sampleType: "EDTA Whole Blood",
    method: "Rapid Immunochromatographic Test",
    subTests: [
      { name: "P. vivax (HRP2 Antigen)", reference: "Negative", method: "ICT" },
      { name: "P. falciparum (pLDH Antigen)", reference: "Negative", method: "ICT" },
      { name: "Pan Malaria (All Species)", reference: "Negative", method: "ICT" },
    ],
  },
  {
    id: "hiv",
    name: "HIV I & II Antibody Screening",
    category: "Serology",
    department: "DEPARTMENT OF CLINICAL MICROBIOLOGY & SEROLOGY",
    cost: 400,
    sampleType: "Serum",
    method: "CLIA / Rapid",
    subTests: [
      { name: "HIV I Antibody", reference: "Non-Reactive", method: "CLIA" },
      { name: "HIV II Antibody", reference: "Non-Reactive", method: "CLIA" },
      { name: "HIV p24 Antigen", reference: "Non-Reactive", method: "CLIA" },
    ],
    comments: "This is a screening test. Reactive results should be confirmed by Western Blot or NAT test.",
  },
  {
    id: "hbsag",
    name: "HBsAg (Hepatitis B Surface Antigen)",
    category: "Serology",
    department: "DEPARTMENT OF CLINICAL MICROBIOLOGY & SEROLOGY",
    cost: 350,
    sampleType: "Serum",
    method: "CLIA (Chemiluminescent Immunoassay)",
    subTests: [
      { name: "HBsAg (Hepatitis B Surface Antigen)", reference: "Non-Reactive", method: "CLIA" },
      { name: "Anti-HBs (Hepatitis B Surface Antibody)", unit: "mIU/mL", reference: "< 10 (Non-immune)\n>= 10 (Immune)", method: "CLIA" },
      { name: "Anti-HBc IgM (Core Antibody IgM)", reference: "Non-Reactive", method: "CLIA" },
      { name: "Anti-HBc Total (Core Antibody)", reference: "Non-Reactive", method: "CLIA" },
      { name: "HBeAg (Hepatitis B e-Antigen)", reference: "Non-Reactive", method: "CLIA" },
      { name: "Anti-HBe (Hepatitis B e-Antibody)", reference: "Non-Reactive", method: "CLIA" },
    ],
  },
  {
    id: "iron_studies",
    name: "Iron Studies (Iron Profile)",
    category: "Biochemistry",
    department: "DEPARTMENT OF CLINICAL BIOCHEMISTRY AND IMMUNOCHEMISTRY",
    cost: 650,
    sampleType: "Serum (Fasting)",
    method: "Colorimetric / Immunoturbidimetry",
    subTests: [
      { name: "Serum Iron", unit: "µg/dL", reference: "60 - 170 (M) / 50 - 150 (F)", method: "Ferrozine" },
      { name: "TIBC (Total Iron Binding Capacity)", unit: "µg/dL", reference: "240 - 450", method: "Colorimetric" },
      { name: "UIBC (Unsaturated Iron Binding Capacity)", unit: "µg/dL", reference: "150 - 375", method: "Calculated" },
      { name: "Transferrin Saturation", unit: "%", reference: "20 - 50 (M) / 15 - 50 (F)", method: "Calculated" },
      { name: "Serum Ferritin", unit: "ng/mL", reference: "12 - 300 (M) / 12 - 150 (F)", method: "CLIA" },
    ],
  },
  {
    id: "coagulation",
    name: "Coagulation Profile",
    category: "Hematology",
    department: "DEPARTMENT OF HEMATOLOGY",
    cost: 700,
    sampleType: "Citrate Plasma (3.2% Sodium Citrate)",
    method: "Automated Coagulation Analyzer",
    subTests: [
      { name: "Prothrombin Time (PT)", unit: "seconds", reference: "11 - 13.5", method: "Clot Detection" },
      { name: "INR (International Normalised Ratio)", unit: "", reference: "0.8 - 1.2 (Not on anticoagulants)\nTherapeutic: 2.0 - 3.0", method: "Calculated" },
      { name: "APTT (Activated Partial Thromboplastin Time)", unit: "seconds", reference: "25 - 38", method: "Clot Detection" },
      { name: "Thrombin Time (TT)", unit: "seconds", reference: "14 - 21", method: "Clot Detection" },
      { name: "Fibrinogen", unit: "mg/dL", reference: "200 - 400", method: "Clauss" },
      { name: "D-Dimer", unit: "ng/mL", reference: "< 500", method: "Immunoturbidimetry" },
    ],
  },
  {
    id: "cardiac_markers",
    name: "Cardiac Risk Markers",
    category: "Biochemistry",
    department: "DEPARTMENT OF CLINICAL BIOCHEMISTRY AND IMMUNOCHEMISTRY",
    cost: 1500,
    sampleType: "Serum",
    method: "CLIA",
    subTests: [
      { name: "Troponin I (cTnI)", unit: "ng/mL", reference: "< 0.04 (Normal)\n0.04-0.1 (Borderline)\n> 0.1 (Elevated)", method: "CLIA" },
      { name: "Troponin T (cTnT)", unit: "ng/mL", reference: "< 0.01", method: "CLIA" },
      { name: "CK-MB (Creatine Kinase MB)", unit: "ng/mL", reference: "< 5.0", method: "CLIA" },
      { name: "Total CK (Creatine Kinase)", unit: "U/L", reference: "24 - 195 (M) / 24 - 170 (F)", method: "IFCC" },
      { name: "Myoglobin", unit: "ng/mL", reference: "< 90 (M) / < 70 (F)", method: "CLIA" },
      { name: "hs-CRP (High Sensitivity CRP)", unit: "mg/L", reference: "Low Risk: < 1.0\nAverage: 1.0-3.0\nHigh Risk: > 3.0", method: "Immunoturbidimetry" },
      { name: "BNP (Brain Natriuretic Peptide)", unit: "pg/mL", reference: "< 100 (Normal Heart Function)", method: "CLIA" },
      { name: "Homocysteine", unit: "µmol/L", reference: "5 - 15 (Normal)\n15-30 (Moderate Elevation)", method: "CLIA" },
    ],
  },
  {
    id: "peripheral_smear",
    name: "Peripheral Blood Smear (PS)",
    category: "Hematology",
    department: "DEPARTMENT OF HEMATOLOGY",
    cost: 250,
    sampleType: "EDTA Whole Blood",
    method: "Leishman / Giemsa Stain Microscopy",
    subTests: [
      { name: "RBC Morphology", reference: "Normocytic Normochromic", method: "Microscopy" },
      { name: "Anisocytosis", reference: "Absent", method: "Microscopy" },
      { name: "Poikilocytosis", reference: "Absent", method: "Microscopy" },
      { name: "Microcytes", reference: "Absent", method: "Microscopy" },
      { name: "Macrocytes", reference: "Absent", method: "Microscopy" },
      { name: "Hypochromia", reference: "Absent", method: "Microscopy" },
      { name: "Target Cells", reference: "Absent", method: "Microscopy" },
      { name: "WBC Morphology", reference: "Normal in number & morphology", method: "Microscopy" },
      { name: "Platelet Morphology", reference: "Adequate on smear", method: "Microscopy" },
      { name: "Hemoparasites", reference: "Not seen", method: "Microscopy" },
      { name: "Impression", reference: "—", method: "Microscopy" },
    ],
  },
  {
    id: "reticulocyte",
    name: "Reticulocyte Count",
    category: "Hematology",
    department: "DEPARTMENT OF HEMATOLOGY",
    cost: 250,
    sampleType: "EDTA Whole Blood",
    method: "Supravital Stain (New Methylene Blue)",
    subTests: [
      { name: "Reticulocyte Count", unit: "%", reference: "0.5 - 2.5", method: "Microscopy" },
      { name: "Absolute Reticulocyte Count", unit: "x10^9/L", reference: "25 - 75", method: "Calculated" },
      { name: "Corrected Reticulocyte Count", unit: "%", reference: "0.5 - 1.5", method: "Calculated" },
    ],
  },
  {
    id: "hb_electrophoresis",
    name: "Hemoglobin Electrophoresis (HPLC)",
    category: "Hematology",
    department: "DEPARTMENT OF HEMATOLOGY",
    cost: 1500,
    sampleType: "EDTA Whole Blood",
    method: "HPLC (Bio-Rad Variant)",
    subTests: [
      { name: "HbA", unit: "%", reference: "96.5 - 97.5", method: "HPLC" },
      { name: "HbA2", unit: "%", reference: "2.0 - 3.5", method: "HPLC" },
      { name: "HbF (Fetal Hemoglobin)", unit: "%", reference: "< 2.0 (Adult)", method: "HPLC" },
      { name: "HbS (Sickle)", unit: "%", reference: "Absent", method: "HPLC" },
      { name: "HbC", unit: "%", reference: "Absent", method: "HPLC" },
      { name: "HbE", unit: "%", reference: "Absent", method: "HPLC" },
      { name: "Interpretation", reference: "Normal Adult Pattern", method: "HPLC" },
    ],
  },
  {
    id: "blood_group",
    name: "Blood Group & Rh Typing",
    category: "Immunohematology",
    department: "DEPARTMENT OF BLOOD BANK & TRANSFUSION MEDICINE",
    cost: 100,
    sampleType: "EDTA Whole Blood",
    method: "Slide / Tube Agglutination",
    subTests: [
      { name: "ABO Blood Group", reference: "A / B / AB / O", method: "Agglutination" },
      { name: "Rh (D) Typing", reference: "Positive / Negative", method: "Agglutination" },
    ],
  },
  {
    id: "stool_routine",
    name: "Stool Routine & Microscopy",
    category: "Clinical Pathology",
    department: "DEPARTMENT OF CLINICAL PATHOLOGY",
    cost: 200,
    sampleType: "Stool",
    subTests: [
      { name: "Colour", reference: "Brown" },
      { name: "Consistency", reference: "Soft / Formed" },
      { name: "Mucus", reference: "Absent" },
      { name: "Blood", reference: "Absent" },
      { name: "Worms / Segments", reference: "Not Seen" },
      { name: "Reaction (pH)", reference: "6.0 - 7.5" },
      { name: "Occult Blood", reference: "Negative" },
      { name: "Reducing Substance", reference: "Negative" },
      { name: "Pus Cells", unit: "/hpf", reference: "0 - 2" },
      { name: "RBC", unit: "/hpf", reference: "Absent" },
      { name: "Epithelial Cells", unit: "/hpf", reference: "0 - 2" },
      { name: "Ova / Cyst / Parasite", reference: "Not Seen" },
      { name: "Yeast Cells", reference: "Absent" },
      { name: "Vegetable Fibres", reference: "Few" },
      { name: "Starch Granules", reference: "Absent" },
      { name: "Fat Globules", reference: "Absent" },
    ],
  },
  {
    id: "semen_analysis",
    name: "Semen Analysis (WHO 2021)",
    category: "Clinical Pathology",
    department: "DEPARTMENT OF CLINICAL PATHOLOGY",
    cost: 600,
    sampleType: "Semen (after 2-7 days abstinence)",
    method: "Manual / CASA",
    subTests: [
      { name: "Volume", unit: "mL", reference: ">= 1.4" },
      { name: "Colour", reference: "Grayish White" },
      { name: "Liquefaction Time", unit: "min", reference: "< 30" },
      { name: "Viscosity", reference: "Normal" },
      { name: "pH", reference: ">= 7.2" },
      { name: "Sperm Concentration", unit: "million/mL", reference: ">= 16" },
      { name: "Total Sperm Count", unit: "million/ejaculate", reference: ">= 39" },
      { name: "Total Motility", unit: "%", reference: ">= 42" },
      { name: "Progressive Motility", unit: "%", reference: ">= 30" },
      { name: "Non-Progressive Motility", unit: "%", reference: "—" },
      { name: "Immotile Sperms", unit: "%", reference: "< 58" },
      { name: "Sperm Vitality", unit: "%", reference: ">= 54" },
      { name: "Normal Morphology", unit: "%", reference: ">= 4" },
      { name: "Pus Cells (WBC)", unit: "million/mL", reference: "< 1.0" },
      { name: "RBC", reference: "Absent" },
      { name: "Agglutination", reference: "Absent" },
    ],
  },
  {
    id: "beta_hcg",
    name: "Beta hCG (Pregnancy Test - Quantitative)",
    category: "Endocrinology",
    department: "DEPARTMENT OF CLINICAL IMMUNOLOGY & SEROLOGY",
    cost: 600,
    sampleType: "Serum",
    method: "CLIA",
    subTests: [
      { name: "Beta hCG (Quantitative)", unit: "mIU/mL", reference: "Non-pregnant: < 5\nPregnant (4w): 5 - 426\n(5w): 19 - 7340\n(6w): 1080 - 56500\n(7-8w): 7650 - 229000\n(2nd Trimester): 25700 - 288000\n(3rd Trimester): 3640 - 117000", method: "CLIA" },
    ],
  },
  {
    id: "psa",
    name: "Prostate Specific Antigen (PSA)",
    category: "Tumor Markers",
    department: "DEPARTMENT OF CLINICAL IMMUNOLOGY & SEROLOGY",
    cost: 700,
    sampleType: "Serum",
    method: "CLIA",
    subTests: [
      { name: "Total PSA", unit: "ng/mL", reference: "< 4.0 (Age < 50)\n< 4.5 (50-59)\n< 5.5 (60-69)\n< 6.5 (>= 70)", method: "CLIA" },
      { name: "Free PSA", unit: "ng/mL", reference: "Method dependent", method: "CLIA" },
      { name: "Free/Total PSA Ratio", unit: "%", reference: "> 25 (Benign)\n< 10 (Suspicious for Cancer)", method: "Calculated" },
    ],
  },
  {
    id: "tumor_markers",
    name: "Tumor Marker Panel",
    category: "Tumor Markers",
    department: "DEPARTMENT OF CLINICAL IMMUNOLOGY & SEROLOGY",
    cost: 3500,
    sampleType: "Serum",
    method: "CLIA",
    subTests: [
      { name: "AFP (Alpha Feto Protein)", unit: "ng/mL", reference: "< 10", method: "CLIA" },
      { name: "CEA (Carcinoembryonic Antigen)", unit: "ng/mL", reference: "< 3.0 (Non-smoker)\n< 5.0 (Smoker)", method: "CLIA" },
      { name: "CA 125", unit: "U/mL", reference: "< 35", method: "CLIA" },
      { name: "CA 19-9", unit: "U/mL", reference: "< 37", method: "CLIA" },
      { name: "CA 15-3", unit: "U/mL", reference: "< 31.3", method: "CLIA" },
      { name: "Beta-2 Microglobulin", unit: "mg/L", reference: "0.8 - 2.2", method: "CLIA" },
    ],
  },
  {
    id: "hormone_female",
    name: "Female Hormone Panel",
    category: "Endocrinology",
    department: "DEPARTMENT OF CLINICAL IMMUNOLOGY & SEROLOGY",
    cost: 2200,
    sampleType: "Serum",
    method: "CLIA",
    subTests: [
      { name: "FSH (Follicle Stimulating Hormone)", unit: "mIU/mL", reference: "Follicular: 3.5-12.5\nOvulation: 4.7-21.5\nLuteal: 1.7-7.7\nPost-menopausal: 25.8-134.8", method: "CLIA" },
      { name: "LH (Luteinizing Hormone)", unit: "mIU/mL", reference: "Follicular: 2.4-12.6\nOvulation: 14-95.6\nLuteal: 1.0-11.4\nPost-menopausal: 7.7-58.5", method: "CLIA" },
      { name: "Prolactin", unit: "ng/mL", reference: "4.79 - 23.3 (Non-pregnant)", method: "CLIA" },
      { name: "Estradiol (E2)", unit: "pg/mL", reference: "Follicular: 12.5-166\nOvulation: 85.8-498\nLuteal: 43.8-211\nPost-menopausal: < 54.7", method: "CLIA" },
      { name: "Progesterone", unit: "ng/mL", reference: "Follicular: < 0.89\nOvulation: < 12\nLuteal: 1.8-23.9\nPost-menopausal: < 0.20", method: "CLIA" },
      { name: "AMH (Anti-Mullerian Hormone)", unit: "ng/mL", reference: "1.0 - 4.0 (Reproductive)", method: "CLIA" },
    ],
  },
  {
    id: "hormone_male",
    name: "Male Hormone Panel",
    category: "Endocrinology",
    department: "DEPARTMENT OF CLINICAL IMMUNOLOGY & SEROLOGY",
    cost: 1800,
    sampleType: "Serum",
    method: "CLIA",
    subTests: [
      { name: "Total Testosterone", unit: "ng/dL", reference: "240 - 950", method: "CLIA" },
      { name: "Free Testosterone", unit: "pg/mL", reference: "47 - 244", method: "CLIA" },
      { name: "DHEA-S", unit: "µg/dL", reference: "80 - 560", method: "CLIA" },
      { name: "SHBG (Sex Hormone Binding Globulin)", unit: "nmol/L", reference: "18.3 - 54.1", method: "CLIA" },
      { name: "FSH", unit: "mIU/mL", reference: "1.5 - 12.4", method: "CLIA" },
      { name: "LH", unit: "mIU/mL", reference: "1.7 - 8.6", method: "CLIA" },
      { name: "Prolactin", unit: "ng/mL", reference: "4.04 - 15.2", method: "CLIA" },
    ],
  },
  {
    id: "cortisol",
    name: "Cortisol (AM / PM)",
    category: "Endocrinology",
    department: "DEPARTMENT OF CLINICAL IMMUNOLOGY & SEROLOGY",
    cost: 700,
    sampleType: "Serum",
    method: "CLIA",
    subTests: [
      { name: "Cortisol - Morning (8 AM)", unit: "µg/dL", reference: "6.2 - 19.4", method: "CLIA" },
      { name: "Cortisol - Evening (4 PM)", unit: "µg/dL", reference: "2.3 - 11.9", method: "CLIA" },
    ],
  },
  {
    id: "insulin",
    name: "Insulin (Fasting & PP)",
    category: "Endocrinology",
    department: "DEPARTMENT OF CLINICAL IMMUNOLOGY & SEROLOGY",
    cost: 900,
    sampleType: "Serum",
    method: "CLIA",
    subTests: [
      { name: "Insulin - Fasting", unit: "µIU/mL", reference: "2.6 - 24.9", method: "CLIA" },
      { name: "Insulin - 2 Hr Postprandial", unit: "µIU/mL", reference: "< 166", method: "CLIA" },
      { name: "C-Peptide", unit: "ng/mL", reference: "1.1 - 4.4 (Fasting)", method: "CLIA" },
      { name: "HOMA-IR (Insulin Resistance Index)", unit: "", reference: "< 2.5", method: "Calculated" },
    ],
  },
  {
    id: "pth",
    name: "Parathyroid Hormone (Intact PTH)",
    category: "Endocrinology",
    department: "DEPARTMENT OF CLINICAL IMMUNOLOGY & SEROLOGY",
    cost: 900,
    sampleType: "Serum (EDTA preferred)",
    method: "CLIA",
    subTests: [
      { name: "Intact PTH", unit: "pg/mL", reference: "15 - 65", method: "CLIA" },
      { name: "Ionized Calcium", unit: "mmol/L", reference: "1.12 - 1.32", method: "ISE" },
    ],
  },
  {
    id: "electrolytes",
    name: "Serum Electrolytes",
    category: "Biochemistry",
    department: "DEPARTMENT OF CLINICAL BIOCHEMISTRY AND IMMUNOCHEMISTRY",
    cost: 250,
    sampleType: "Serum",
    method: "Ion Selective Electrode (ISE)",
    subTests: [
      { name: "Sodium (Na+)", unit: "mmol/L", reference: "135 - 145", method: "ISE" },
      { name: "Potassium (K+)", unit: "mmol/L", reference: "3.5 - 5.1", method: "ISE" },
      { name: "Chloride (Cl-)", unit: "mmol/L", reference: "98 - 107", method: "ISE" },
      { name: "Bicarbonate (HCO3-)", unit: "mmol/L", reference: "22 - 29", method: "ISE" },
      { name: "Anion Gap", unit: "mmol/L", reference: "8 - 16", method: "Calculated" },
    ],
  },
  {
    id: "abg",
    name: "Arterial Blood Gas (ABG)",
    category: "Biochemistry",
    department: "DEPARTMENT OF CLINICAL BIOCHEMISTRY AND IMMUNOCHEMISTRY",
    cost: 600,
    sampleType: "Heparinised Arterial Blood",
    method: "Blood Gas Analyzer",
    subTests: [
      { name: "pH", reference: "7.35 - 7.45", method: "Electrode" },
      { name: "pCO2", unit: "mmHg", reference: "35 - 45", method: "Electrode" },
      { name: "pO2", unit: "mmHg", reference: "80 - 100", method: "Electrode" },
      { name: "HCO3- (Actual)", unit: "mmol/L", reference: "22 - 26", method: "Calculated" },
      { name: "Base Excess (BE)", unit: "mmol/L", reference: "-2 to +2", method: "Calculated" },
      { name: "O2 Saturation (SaO2)", unit: "%", reference: "94 - 100", method: "Calculated" },
      { name: "Lactate", unit: "mmol/L", reference: "0.5 - 2.2", method: "Enzymatic" },
    ],
  },
  {
    id: "amylase_lipase",
    name: "Pancreatic Profile (Amylase / Lipase)",
    category: "Biochemistry",
    department: "DEPARTMENT OF CLINICAL BIOCHEMISTRY AND IMMUNOCHEMISTRY",
    cost: 500,
    sampleType: "Serum",
    method: "Enzymatic",
    subTests: [
      { name: "Serum Amylase", unit: "U/L", reference: "25 - 125", method: "CNPG3" },
      { name: "Serum Lipase", unit: "U/L", reference: "13 - 60", method: "Colorimetric" },
    ],
  },
  {
    id: "ana",
    name: "ANA (Antinuclear Antibody)",
    category: "Immunology",
    department: "DEPARTMENT OF CLINICAL IMMUNOLOGY & SEROLOGY",
    cost: 800,
    sampleType: "Serum",
    method: "IFA (Indirect Immunofluorescence)",
    subTests: [
      { name: "ANA (IFA on HEp-2)", reference: "Negative (< 1:80)", method: "IFA" },
      { name: "ANA Pattern", reference: "—", method: "IFA" },
      { name: "ANA Titre", reference: "< 1:80", method: "IFA" },
    ],
  },
  {
    id: "ra_aso",
    name: "Rheumatoid Profile (RA / ASO / CRP)",
    category: "Immunology",
    department: "DEPARTMENT OF CLINICAL IMMUNOLOGY & SEROLOGY",
    cost: 500,
    sampleType: "Serum",
    method: "Immunoturbidimetry",
    subTests: [
      { name: "RA Factor (Rheumatoid Factor)", unit: "IU/mL", reference: "< 14", method: "Turbidimetry" },
      { name: "Anti-CCP", unit: "U/mL", reference: "< 17", method: "CLIA" },
      { name: "ASO (Anti Streptolysin O)", unit: "IU/mL", reference: "< 200", method: "Turbidimetry" },
      { name: "CRP", unit: "mg/L", reference: "< 6.0", method: "Turbidimetry" },
      { name: "Uric Acid", unit: "mg/dL", reference: "3.5 - 7.2", method: "Uricase" },
    ],
  },
  {
    id: "procalcitonin",
    name: "Procalcitonin (PCT)",
    category: "Immunology",
    department: "DEPARTMENT OF CLINICAL IMMUNOLOGY & SEROLOGY",
    cost: 1200,
    sampleType: "Serum",
    method: "CLIA",
    subTests: [
      { name: "Procalcitonin", unit: "ng/mL", reference: "< 0.05 (Healthy)\n< 0.5 (Low Risk)\n0.5-2 (Possible Sepsis)\n> 2 (Sepsis Likely)", method: "CLIA" },
    ],
  },
  {
    id: "hcv",
    name: "Anti-HCV (Hepatitis C)",
    category: "Serology",
    department: "DEPARTMENT OF CLINICAL MICROBIOLOGY & SEROLOGY",
    cost: 600,
    sampleType: "Serum",
    method: "CLIA",
    subTests: [
      { name: "Anti-HCV Antibody", reference: "Non-Reactive", method: "CLIA" },
      { name: "Cut-off Index (COI)", reference: "< 1.0", method: "CLIA" },
    ],
  },
  {
    id: "hav",
    name: "Hepatitis A (HAV) IgM",
    category: "Serology",
    department: "DEPARTMENT OF CLINICAL MICROBIOLOGY & SEROLOGY",
    cost: 700,
    sampleType: "Serum",
    method: "CLIA",
    subTests: [
      { name: "Anti-HAV IgM", reference: "Non-Reactive", method: "CLIA" },
      { name: "Anti-HAV Total", reference: "Non-Reactive", method: "CLIA" },
    ],
  },
  {
    id: "vdrl",
    name: "VDRL / RPR (Syphilis)",
    category: "Serology",
    department: "DEPARTMENT OF CLINICAL MICROBIOLOGY & SEROLOGY",
    cost: 200,
    sampleType: "Serum",
    method: "Slide Flocculation",
    subTests: [
      { name: "VDRL", reference: "Non-Reactive", method: "Slide Flocculation" },
      { name: "VDRL Titre (if reactive)", reference: "—", method: "Slide Flocculation" },
      { name: "TPHA (Confirmation)", reference: "Non-Reactive", method: "Agglutination" },
    ],
  },
  {
    id: "covid_ab",
    name: "COVID-19 Antibody (IgG)",
    category: "Serology",
    department: "DEPARTMENT OF CLINICAL MICROBIOLOGY & SEROLOGY",
    cost: 500,
    sampleType: "Serum",
    method: "CLIA",
    subTests: [
      { name: "SARS-CoV-2 IgG (Spike)", unit: "AU/mL", reference: "< 50 (Negative)\n>= 50 (Positive)", method: "CLIA" },
      { name: "SARS-CoV-2 IgM", reference: "Non-Reactive", method: "CLIA" },
    ],
  },
  {
    id: "g6pd",
    name: "G6PD (Glucose-6-Phosphate Dehydrogenase)",
    category: "Hematology",
    department: "DEPARTMENT OF HEMATOLOGY",
    cost: 600,
    sampleType: "EDTA Whole Blood",
    method: "Quantitative (UV Kinetic)",
    subTests: [
      { name: "G6PD Activity", unit: "U/g Hb", reference: "6.4 - 18.7", method: "UV Kinetic" },
    ],
    comments: "Patients with G6PD deficiency may develop hemolysis when exposed to certain drugs, infections, or fava beans.",
  },
  {
    id: "sickle_cell",
    name: "Sickle Cell Screening",
    category: "Hematology",
    department: "DEPARTMENT OF HEMATOLOGY",
    cost: 300,
    sampleType: "EDTA Whole Blood",
    method: "Sodium Metabisulphite",
    subTests: [
      { name: "Sickling Test", reference: "Negative", method: "Slide Method" },
      { name: "Solubility Test", reference: "Negative", method: "Solubility" },
    ],
  },
];
