export type SubTest = {
  name: string;
  unit?: string;
  reference?: string;
};

export type PathologyTest = {
  id: string;
  name: string;
  category: string;
  cost: number;
  sampleType: string;
  method?: string;
  subTests?: SubTest[];
};

export const PATHOLOGY_TESTS: PathologyTest[] = [
  {
    id: "cbc",
    name: "Complete Blood Count (CBC)",
    category: "Hematology",
    cost: 350,
    sampleType: "EDTA Whole Blood",
    method: "Automated Cell Counter",
    subTests: [
      { name: "Hemoglobin", unit: "g/dL", reference: "13.0 - 17.0" },
      { name: "Total RBC Count", unit: "million/µL", reference: "4.5 - 5.5" },
      { name: "Total WBC Count", unit: "/µL", reference: "4000 - 11000" },
      { name: "Platelet Count", unit: "lakhs/µL", reference: "1.5 - 4.5" },
      { name: "Hematocrit (PCV)", unit: "%", reference: "40 - 50" },
      { name: "MCV", unit: "fL", reference: "80 - 100" },
      { name: "MCH", unit: "pg", reference: "27 - 32" },
      { name: "MCHC", unit: "g/dL", reference: "32 - 36" },
      { name: "Neutrophils", unit: "%", reference: "40 - 70" },
      { name: "Lymphocytes", unit: "%", reference: "20 - 40" },
      { name: "Eosinophils", unit: "%", reference: "1 - 6" },
      { name: "Monocytes", unit: "%", reference: "2 - 10" },
      { name: "Basophils", unit: "%", reference: "0 - 1" },
    ],
  },
  {
    id: "lft",
    name: "Liver Function Test (LFT)",
    category: "Biochemistry",
    cost: 600,
    sampleType: "Serum",
    method: "Spectrophotometry",
    subTests: [
      { name: "Total Bilirubin", unit: "mg/dL", reference: "0.2 - 1.2" },
      { name: "Direct Bilirubin", unit: "mg/dL", reference: "0.0 - 0.3" },
      { name: "Indirect Bilirubin", unit: "mg/dL", reference: "0.1 - 0.9" },
      { name: "SGOT (AST)", unit: "U/L", reference: "5 - 40" },
      { name: "SGPT (ALT)", unit: "U/L", reference: "5 - 45" },
      { name: "Alkaline Phosphatase", unit: "U/L", reference: "40 - 130" },
      { name: "Total Protein", unit: "g/dL", reference: "6.0 - 8.3" },
      { name: "Albumin", unit: "g/dL", reference: "3.5 - 5.2" },
      { name: "Globulin", unit: "g/dL", reference: "2.0 - 3.5" },
      { name: "A/G Ratio", unit: "", reference: "1.0 - 2.1" },
    ],
  },
  {
    id: "kft",
    name: "Kidney Function Test (KFT)",
    category: "Biochemistry",
    cost: 550,
    sampleType: "Serum",
    method: "Spectrophotometry",
    subTests: [
      { name: "Blood Urea", unit: "mg/dL", reference: "15 - 40" },
      { name: "Serum Creatinine", unit: "mg/dL", reference: "0.7 - 1.3" },
      { name: "Uric Acid", unit: "mg/dL", reference: "3.5 - 7.2" },
      { name: "Sodium", unit: "mmol/L", reference: "135 - 145" },
      { name: "Potassium", unit: "mmol/L", reference: "3.5 - 5.1" },
      { name: "Chloride", unit: "mmol/L", reference: "98 - 107" },
      { name: "Calcium", unit: "mg/dL", reference: "8.6 - 10.2" },
    ],
  },
  {
    id: "lipid",
    name: "Lipid Profile",
    category: "Biochemistry",
    cost: 500,
    sampleType: "Serum (Fasting)",
    method: "Enzymatic",
    subTests: [
      { name: "Total Cholesterol", unit: "mg/dL", reference: "< 200" },
      { name: "Triglycerides", unit: "mg/dL", reference: "< 150" },
      { name: "HDL Cholesterol", unit: "mg/dL", reference: "> 40" },
      { name: "LDL Cholesterol", unit: "mg/dL", reference: "< 100" },
      { name: "VLDL Cholesterol", unit: "mg/dL", reference: "< 30" },
      { name: "Total Cholesterol / HDL Ratio", unit: "", reference: "< 4.5" },
    ],
  },
  {
    id: "thyroid",
    name: "Thyroid Profile (T3, T4, TSH)",
    category: "Endocrinology",
    cost: 450,
    sampleType: "Serum",
    method: "CLIA",
    subTests: [
      { name: "Total T3", unit: "ng/mL", reference: "0.8 - 2.0" },
      { name: "Total T4", unit: "µg/dL", reference: "5.1 - 14.1" },
      { name: "TSH", unit: "µIU/mL", reference: "0.27 - 4.20" },
    ],
  },
  {
    id: "fbs",
    name: "Fasting Blood Sugar",
    category: "Biochemistry",
    cost: 100,
    sampleType: "Fluoride Plasma",
    method: "GOD-POD",
    subTests: [
      { name: "Glucose - Fasting", unit: "mg/dL", reference: "70 - 100" },
    ],
  },
  {
    id: "ppbs",
    name: "Postprandial Blood Sugar",
    category: "Biochemistry",
    cost: 100,
    sampleType: "Fluoride Plasma",
    method: "GOD-POD",
    subTests: [
      { name: "Glucose - PP (2hrs)", unit: "mg/dL", reference: "< 140" },
    ],
  },
  {
    id: "hba1c",
    name: "HbA1c (Glycated Hemoglobin)",
    category: "Biochemistry",
    cost: 450,
    sampleType: "EDTA Whole Blood",
    method: "HPLC",
    subTests: [
      { name: "HbA1c", unit: "%", reference: "4.0 - 5.6" },
      { name: "Estimated Avg Glucose", unit: "mg/dL", reference: "70 - 126" },
    ],
  },
  {
    id: "urine",
    name: "Urine Routine Examination",
    category: "Clinical Pathology",
    cost: 200,
    sampleType: "Random Urine",
    subTests: [
      { name: "Colour", reference: "Pale Yellow" },
      { name: "Appearance", reference: "Clear" },
      { name: "pH", reference: "5.0 - 8.0" },
      { name: "Specific Gravity", reference: "1.005 - 1.030" },
      { name: "Protein", reference: "Nil" },
      { name: "Glucose", reference: "Nil" },
      { name: "Ketones", reference: "Nil" },
      { name: "Pus Cells", unit: "/hpf", reference: "0 - 5" },
      { name: "RBCs", unit: "/hpf", reference: "0 - 2" },
      { name: "Epithelial Cells", unit: "/hpf", reference: "0 - 5" },
    ],
  },
  {
    id: "vitd",
    name: "Vitamin D (25-OH)",
    category: "Endocrinology",
    cost: 1200,
    sampleType: "Serum",
    method: "CLIA",
    subTests: [{ name: "25-OH Vitamin D", unit: "ng/mL", reference: "30 - 100" }],
  },
  {
    id: "vitb12",
    name: "Vitamin B12",
    category: "Endocrinology",
    cost: 800,
    sampleType: "Serum",
    method: "CLIA",
    subTests: [{ name: "Vitamin B12", unit: "pg/mL", reference: "211 - 911" }],
  },
  {
    id: "esr",
    name: "ESR (Erythrocyte Sedimentation Rate)",
    category: "Hematology",
    cost: 100,
    sampleType: "EDTA Whole Blood",
    method: "Westergren",
    subTests: [{ name: "ESR", unit: "mm/hr", reference: "0 - 20" }],
  },
  {
    id: "crp",
    name: "C-Reactive Protein (CRP)",
    category: "Immunology",
    cost: 350,
    sampleType: "Serum",
    method: "Turbidimetry",
    subTests: [{ name: "CRP", unit: "mg/L", reference: "< 6.0" }],
  },
  {
    id: "dengue",
    name: "Dengue NS1 + IgG/IgM",
    category: "Serology",
    cost: 900,
    sampleType: "Serum",
    method: "ELISA / Rapid",
    subTests: [
      { name: "Dengue NS1 Antigen", reference: "Negative" },
      { name: "Dengue IgM", reference: "Negative" },
      { name: "Dengue IgG", reference: "Negative" },
    ],
  },
  {
    id: "typhi",
    name: "Widal Test",
    category: "Serology",
    cost: 250,
    sampleType: "Serum",
    method: "Slide Agglutination",
    subTests: [
      { name: "S. Typhi O", reference: "< 1:80" },
      { name: "S. Typhi H", reference: "< 1:80" },
      { name: "S. Paratyphi AH", reference: "< 1:80" },
      { name: "S. Paratyphi BH", reference: "< 1:80" },
    ],
  },
  {
    id: "malaria",
    name: "Malaria Parasite (Rapid)",
    category: "Serology",
    cost: 250,
    sampleType: "EDTA Whole Blood",
    subTests: [
      { name: "P. vivax", reference: "Negative" },
      { name: "P. falciparum", reference: "Negative" },
    ],
  },
  {
    id: "hiv",
    name: "HIV I & II Antibody",
    category: "Serology",
    cost: 400,
    sampleType: "Serum",
    method: "Rapid / CLIA",
    subTests: [{ name: "HIV I & II Antibody", reference: "Non-Reactive" }],
  },
  {
    id: "hbsag",
    name: "HBsAg (Hepatitis B)",
    category: "Serology",
    cost: 350,
    sampleType: "Serum",
    method: "Rapid / CLIA",
    subTests: [{ name: "HBsAg", reference: "Non-Reactive" }],
  },
];
